### ISSUE TITLE
Doing horrible things to Javascript

### ISSUE THREAD

**Issue by franciscop** [tokyojs/tokyojs.github.io#11]
# Doing horrible things to Javascript

### Introduction

I love playing with Javascript. This includes testing its limits and reaching to places better left alone, so I'd love to show a bit of it. Modifying the prototypes is common but I did it in a way that haven't been talked about but that yield surprisingly clean code. Please don't use it in production (;

***

Alternative

***

# From Open Source to freelancer

### Introduction

I have launched many open source projects with varying degrees of popularity, including [Picnic CSS](http://picnicss.com/) and [Umbrella JS](http://umbrellajs.com/). After the last one was launched, a company from US contacted me and I've been working as a freelancer ever since. I made the front-end of http://angularattack.com/, and worked with other people on Andreessen Horowitz and Sequoia Capital websites.

### Presentation Details
**Speaker Name**: Francisco Presencia
**Duration**: 20min

## Extra

- How many people will there be? To know if I should prepare it better as a conversation (few people) or just a presentation (large audience). Also I'm a bit shy so I'd like to be ready.

- I am leaving Japan around the beginning-middle of September, so it might be too short time if there's no scheduled talk already before that.

- I'd love to just go there if there's no available spot for a talk or the proposed topics aren't welcome.

**Comment by bucaran** [comment]
Hola @franciscop. Thanks for your submission, but please make your proposal here instead: 
* https://github.com/tokyojs/talks. As for your questions:

> How many people will there be? 

Usually like 30 to 50 people.

> ...so it might be too short time if there's no scheduled talk already before that...

The last event was on August 12th. Next one should be around the same date on September.

**Comment by franciscop** [comment]
Oops sorry, don't know how that slipped
