### ISSUE TITLE
Talk: Sample Speaker Registration

### ISSUE THREAD

**Issue by briandeheus** [tokyojs/tokyojs.github.io#3]
# Implementing Framework XYZ

### Introduction
I want to give talk about Framework XYZ and the experiences I had implementing said framework. I have 6 months of experience using this framework, and I think it's amazing and everyone should use it.

### Presentation Details
**Speaker Name**: Brian de Heus
**Duration**: 15 minutes

**Comment by brj** [comment]
LGTM

**Comment by bucaran** [comment]
I created a new repo https://github.com/tokyojs/talks, let's use it to track speaker registrations there.
