### ISSUE TITLE
Talk: Vue.js in production

### ISSUE THREAD

**Issue by lunardog** [tokyojs/tokyojs.github.io#4]
# Vue.js in production

## Introduction

Vue.js is one of the "smaller siblings" of Angular.js or React. Its strong points are:

 - very easy to pick up and start using instantly
 - scales: very little bootstrapping for small projects, but gets more powerful by adding components
 - DOM updates happen on animation frame requests, which results in high responsiveness in many scenarios.

I'd like to talk about Vue.js itself, show some demo code and shortly present a deployed and well-used app based on Vue.js. 

Here's a demo: https://abecon-3c221.firebaseapp.com/
Code is here: https://github.com/lunardog/MEGAKanban

## Presentation details

**Speaker name:** Leszek Rybicki

**Duration:** 20 minutes

**Comment by briandeheus** [comment]
Hey Leszek, can you speak at the upcoming TokyoJS, on August 12th 19:00? 

Pick a slot and let me know! http://tokyojs.com/

**Comment by lunardog** [comment]
I'd love to. Fine with any slot, so the order makes sense.

I'll keep my talk around 15 minutes if we have many speakers.

**Comment by briandeheus** [comment]
Thanks! You're scheduled for the first talk of the evening.

**Comment by bucaran** [comment]
Thank you for the kind receiving @lunardog! See you again soon.
