### ISSUE TITLE
Talk: RethinkDB & Horizon

### ISSUE THREAD

**Issue by chuck0523** [tokyojs/tokyojs.github.io#6]
# Realtime App made by RethinkDB & Horizon

## Introduction

I'm gonna talk about how to create the real time app by __React, Webpack, Horizon and RethinkDB.__ It's so easy and most importantly fun!

In Japanese community still few people know about them. More and more people should get familiar and used to them!

And in this autumn, developers of RethinkDB and Horizon will come to Japan. They asked me to help. So this is kind of evangelistic activity.

I'm inspired by [this post](https://medium.com/front-end-hacking/react-webpack-and-horizon-quick-start-b9335c1ece53#.7o49t44lz) on Medium.com. 
So I translated it into Japanese for Japanese developers. [Here is the post.](http://qiita.com/chuck0523/items/6e253f6ee53b0f081329)

I'm gonna talk about RethinkDB and Horizon based on the post.

## Presentation Details

Speaker Name: chuck (Twitter [@chuck0523](https://twitter.com/chuck0523) )
Duration: 15 minutes

**Comment by briandeheus** [comment]
RethinkDB fan myself! Happily surprised to see more people are. 😁

**Comment by chuck0523** [comment]
You too?? 😎 
I'm really looking forward to seeing you and talking about it together 🎉

**Comment by bucaran** [comment]
@chuck0523 The next meetup will be the 8/12 at 7 PM, see www.tokyojs.com. If the date works for you let us know please.

**Comment by chuck0523** [comment]
I can make it that day.
I'm looking forward to seeing you all 😎

**Comment by bucaran** [comment]
I'll make you the 2nd speaker then :)

**Comment by briandeheus** [comment]
Next time please also update the website @bucaran ...

**Comment by briandeheus** [comment]
ゲーー. Disregard that. It looks like it's updated but not updated on the website.

**Comment by bucaran** [comment]
Looks fine to me
<img width="445" alt="screenshot 2016-07-28 12 18 21" src="https://cloud.githubusercontent.com/assets/8317250/17200115/6e792bac-54bd-11e6-8948-932b5c4e145d.png">

**Comment by bucaran** [comment]
Thank you for @chuck0523 and good job on your presentation. See you again next time!
