### ISSUE TITLE
Deep Learning by JavaScript

### ISSUE THREAD

**Issue by yujiosaka** [tokyojs/tokyojs.github.io#8]
# Deep Learning by JavaScript

## Introduction

I will talk about how I implemented deep learning by JavaScript.
I made a speech on the same topic in Japanese already.

The slide is here:
https://speakerdeck.com/yujiosaka/hitasurale-sitedeipuraningu

I'll translate that to and speak in English to improve my linguistic skill

## Presentation Details

Speaker Name: Yuji Isobe
Duration: 30 minutes

**Comment by brj** [comment]
Sounds great! Thanks @yujiosaka.

**Comment by lunardog** [comment]
Awesome. Really looking forward to this one.

**Comment by briandeheus** [comment]
Hi @yujiosaka 

Can you speak at the upcoming event, August 12th 19:00?
If you can, pick a slot from here http://tokyojs.com/ and we'll schedule you in!

**Comment by yujiosaka** [comment]
@briandeheus Sure! I'll do!

**Comment by bucaran** [comment]
@yujiosaka Great! I'll add you to the last available slot.

**Comment by bucaran** [comment]
@yujiosaka Great talk man! And thanks for teaching me about neural networks of which I knew nothing about.
