### ISSUE TITLE
Talk: Writing Scalable and Modular CSS with React

### ISSUE THREAD

**Issue by sadiqevani** [tokyojs/tokyojs.github.io#9]
# Writing Scalable and Modular CSS with React

### Introduction
CSS is easy, or might look easy on the outside, since its easy to pickup, but when you have to deal with huge CSS codebases, it becomes a nightmare, since the code starts to couple with everything you do, and to maintain sanity, people create style guides.

In this talk i will provide an overview on how I write scalable and modular CSS with React, that is both fun, and easy to learn, that does not require you to use a lot of "classNames", and mainly has nice syntax and can be documented with the component itself.

### Presentation Details
**Speaker Name**: Sadi Qevani (tw/gh @sadiqevani)
**Duration**: 10-20minute(ish)

**Comment by bucaran** [comment]
Hey @sadiqevani. Looks pretty cool!

**Comment by bucaran** [comment]
@sadiqevani The next meetup will be the 8/12 at 7 PM, see www.tokyojs.com. If the date works for you let us know please.

**Comment by sadiqevani** [comment]
@bucaran I might not be available during that date unfortunately, i have some plans going on by that time. 😫

**Comment by bucaran** [comment]
No worries. Next time then! :)

**Comment by bucaran** [comment]
Moved to https://github.com/tokyojs/talks/issues/3
